import type { DeliveryCard } from './types';

export const INITIAL_CARDS: DeliveryCard[] = [
  {
    id: 'DL-001',
    createdAt: new Date(Date.now() - 1000 * 60 * 45),
    pickup: 'Pharmacie Centrale — 14 rue de Rivoli, Paris 1er',
    dropoff: 'Dr. Élise Morin — 88 avenue Kléber, Paris 16e',
    client: 'CHU Lariboisière',
    phone: '01 49 95 65 65',
    weight: '0.8 kg',
    notes: 'Médicaments sous température contrôlée — conserver entre 2°C et 8°C',
    priority: 'urgent',
    status: 'assigné',
    livreurStatus: 'validé',
    isNew: false,
    scheduledDate: '2026-09-29',
    distanceKm: 4.2,
    patient: 'M. Bernard Fontaine',
    documents: [
      {
        id: 'doc-001-a',
        type: 'ordonnance',
        label: 'Ordonnance médicale',
        reference: 'ORD-2026-09-4471',
        date: '2026-09-22',
        issuer: 'Dr. Claire Vasseur — Oncologie',
        pages: 2,
        confidential: true,
      },
      {
        id: 'doc-001-b',
        type: 'bon_livraison',
        label: 'Bon de livraison',
        reference: 'BL-2026-14802',
        date: '2026-09-24',
        issuer: 'Pharmacie Centrale Paris 1er',
        pages: 1,
        confidential: false,
      },
      {
        id: 'doc-001-c',
        type: 'fiche_patient',
        label: 'Fiche de suivi patient',
        reference: 'FSP-77341',
        date: '2026-09-20',
        issuer: 'Service HAD Lariboisière',
        pages: 3,
        confidential: true,
      },
    ],
  },
  {
    id: 'DL-002',
    createdAt: new Date(Date.now() - 1000 * 60 * 20),
    pickup: 'Labo Biomédical Rive Gauche — 3 place de la République, Paris 3e',
    dropoff: 'Clinique Saint-Michel — 201 rue de Tolbiac, Paris 13e',
    client: 'Réseau de Soins Île-de-France',
    phone: '01 45 88 32 10',
    weight: '1.2 kg',
    notes: 'Prélèvements biologiques — manipuler avec précaution',
    priority: 'standard',
    status: 'nouveau',
    livreurStatus: 'nouveau',
    isNew: false,
    scheduledDate: '2026-09-29',
    distanceKm: 1.8,
    patient: 'Mme Isabelle Renard',
    documents: [
      {
        id: 'doc-002-a',
        type: 'ordonnance',
        label: 'Prescription de transport',
        reference: 'ORD-2026-09-3890',
        date: '2026-09-23',
        issuer: 'Dr. Marc Thuillier — Biologie médicale',
        pages: 1,
        confidential: true,
      },
      {
        id: 'doc-002-b',
        type: 'bon_livraison',
        label: 'Bon de livraison labo',
        reference: 'BL-2026-14803',
        date: '2026-09-24',
        issuer: 'Labo Biomédical Rive Gauche',
        pages: 1,
        confidential: false,
      },
    ],
  },
  {
    id: 'DL-004',
    createdAt: new Date(Date.now() - 1000 * 60 * 5),
    pickup: 'Hôpital Bichat — 46 rue Henri Huchard, Paris 18e',
    dropoff: 'Clinique Geoffroy Saint-Hilaire — 59 rue Geoffroy Saint-Hilaire, Paris 5e',
    client: 'AP-HP Bichat',
    phone: '01 40 25 80 80',
    weight: '0.3 kg',
    notes: 'Produit sanguin — délai critique 4h — contacter le destinataire à l\'arrivée',
    priority: 'urgent',
    status: 'nouveau',
    livreurStatus: 'nouveau',
    isNew: false,
    scheduledDate: '2026-09-30',
    distanceKm: 3.1,
    patient: 'M. Karim Belkacem',
    documents: [
      {
        id: 'doc-004-a',
        type: 'ordonnance',
        label: 'Prescription transfusionnelle',
        reference: 'ORD-2026-09-4490',
        date: '2026-09-24',
        issuer: 'Dr. Sophie Lemaire — Hématologie',
        pages: 2,
        confidential: true,
      },
      {
        id: 'doc-004-b',
        type: 'bon_livraison',
        label: 'Bon de transport produit sanguin',
        reference: 'BL-2026-14821',
        date: '2026-09-24',
        issuer: 'EFS Île-de-France',
        pages: 1,
        confidential: false,
      },
      {
        id: 'doc-004-c',
        type: 'fiche_patient',
        label: 'Fiche de compatibilité',
        reference: 'FSP-BIC-0441',
        date: '2026-09-24',
        issuer: 'Laboratoire immunologie — Bichat',
        pages: 1,
        confidential: true,
      },
    ],
  },
  {
    id: 'DL-005',
    createdAt: new Date(Date.now() - 1000 * 60 * 90),
    pickup: 'Pharmacie Ledru-Rollin — 102 avenue Ledru-Rollin, Paris 11e',
    dropoff: 'Mme Agathe Collin — 34 rue de la Pompe, Paris 16e',
    client: 'HAD Paris Sud',
    phone: '01 44 12 70 00',
    weight: '2.1 kg',
    notes: '',
    priority: 'standard',
    status: 'en_transit',
    livreurStatus: 'validé',
    isNew: false,
    distanceKm: 6.7,
    patient: 'Mme Agathe Collin',
    documents: [
      {
        id: 'doc-005-a',
        type: 'ordonnance',
        label: 'Ordonnance HAD',
        reference: 'ORD-2026-09-4401',
        date: '2026-09-21',
        issuer: 'Dr. Paul Nguyen — Médecine interne',
        pages: 3,
        confidential: true,
      },
      {
        id: 'doc-005-b',
        type: 'bon_livraison',
        label: 'Bon de livraison domicile',
        reference: 'BL-2026-14798',
        date: '2026-09-24',
        issuer: 'Pharmacie Ledru-Rollin',
        pages: 1,
        confidential: false,
      },
    ],
  },
  {
    id: 'DL-006',
    createdAt: new Date(Date.now() - 1000 * 60 * 130),
    pickup: 'Institut Curie — 26 rue d\'Ulm, Paris 5e',
    dropoff: 'Labo Cerba — 9 avenue de l\'Europe, Saint-Ouen-l\'Aumône (95)',
    client: 'Institut Curie',
    phone: '01 56 24 55 55',
    weight: '0.5 kg',
    notes: 'Biopsies — conditions cryogéniques — ne pas congeler',
    priority: 'urgent',
    status: 'livré',
    livreurStatus: 'validé',
    isNew: false,
    scheduledDate: '2026-10-01',
    distanceKm: 0.9,
    patient: 'Mme Françoise Aubert',
    documents: [
      {
        id: 'doc-006-a',
        type: 'ordonnance',
        label: 'Demande d\'analyse anatomopathologique',
        reference: 'ORD-2026-09-4388',
        date: '2026-09-23',
        issuer: 'Dr. Antoine Brière — Oncologie chirurgicale',
        pages: 1,
        confidential: true,
      },
      {
        id: 'doc-006-b',
        type: 'bon_livraison',
        label: 'Bordereau de transport biologique',
        reference: 'BL-2026-14789',
        date: '2026-09-23',
        issuer: 'Institut Curie — Bloc opératoire',
        pages: 2,
        confidential: false,
      },
      {
        id: 'doc-006-c',
        type: 'fiche_patient',
        label: 'Compte-rendu opératoire',
        reference: 'FSP-CUR-2209',
        date: '2026-09-23',
        issuer: 'Dr. Antoine Brière',
        pages: 4,
        confidential: true,
      },
    ],
  },
  {
    id: 'DL-007',
    createdAt: new Date(Date.now() - 1000 * 60 * 12),
    pickup: 'Pharmacie Gare de Lyon — 1 place Louis-Armand, Paris 12e',
    dropoff: 'M. Théodore Blanc — 12 avenue du Général Leclerc, Boulogne-Billancourt',
    client: 'Mutualité Française',
    phone: '06 87 34 21 09',
    weight: '1.8 kg',
    notes: 'Patient sous anticoagulant — document INR joint obligatoire',
    priority: 'standard',
    status: 'nouveau',
    livreurStatus: 'nouveau',
    isNew: false,
    distanceKm: 5.4,
    patient: 'M. Théodore Blanc',
    documents: [
      {
        id: 'doc-007-a',
        type: 'ordonnance',
        label: 'Ordonnance anticoagulant',
        reference: 'ORD-2026-09-4455',
        date: '2026-09-23',
        issuer: 'Dr. Hélène Vidal — Cardiologie',
        pages: 2,
        confidential: true,
      },
      {
        id: 'doc-007-b',
        type: 'fiche_patient',
        label: 'Résultat INR',
        reference: 'FSP-INR-7821',
        date: '2026-09-24',
        issuer: 'Labo Boulogne — Dr. Fauré',
        pages: 1,
        confidential: true,
      },
      {
        id: 'doc-007-c',
        type: 'bon_livraison',
        label: 'Bon de livraison domicile',
        reference: 'BL-2026-14819',
        date: '2026-09-24',
        issuer: 'Pharmacie Gare de Lyon',
        pages: 1,
        confidential: false,
      },
    ],
  },
  {
    id: 'DL-008',
    createdAt: new Date(Date.now() - 1000 * 60 * 200),
    pickup: 'Hôpital Necker — 149 rue de Sèvres, Paris 15e',
    dropoff: 'Hôpital Robert Debré — 48 bd Sérurier, Paris 19e',
    client: 'AP-HP Transfert Inter-Sites',
    phone: '01 44 49 40 00',
    weight: '0.2 kg',
    notes: '',
    priority: 'urgent',
    status: 'livré',
    livreurStatus: 'validé',
    isNew: false,
    distanceKm: 2.3,
    patient: 'Léa Marchetti (pédiatrie)',
    documents: [
      {
        id: 'doc-008-a',
        type: 'ordonnance',
        label: 'Bon de transfert médical',
        reference: 'ORD-2026-09-4320',
        date: '2026-09-23',
        issuer: 'Dr. Camille Roux — Pédiatrie',
        pages: 2,
        confidential: true,
      },
      {
        id: 'doc-008-b',
        type: 'bon_livraison',
        label: 'Bordereau inter-hospitalier',
        reference: 'BL-2026-14770',
        date: '2026-09-23',
        issuer: 'Hôpital Necker — Administration',
        pages: 1,
        confidential: false,
      },
    ],
  },
  {
    id: 'DL-003',
    createdAt: new Date(Date.now() - 1000 * 60 * 8),
    pickup: 'Pharmacie des Batignolles — 52 bd Haussmann, Paris 9e',
    dropoff: 'EHPAD Les Acacias — 7 allée des Acacias, Vincennes',
    client: 'EHPAD Les Acacias',
    phone: '01 43 74 56 12',
    weight: '4.5 kg',
    notes: 'Dotation mensuelle — 12 résidents — liste jointe au bon de livraison',
    priority: 'low',
    status: 'nouveau',
    livreurStatus: 'nouveau',
    isNew: false,
    distanceKm: 8.1,
    patient: 'Dotation collective (12 résidents)',
    documents: [
      {
        id: 'doc-003-a',
        type: 'bon_livraison',
        label: 'Bon de livraison groupé',
        reference: 'BL-2026-14810',
        date: '2026-09-24',
        issuer: 'Pharmacie des Batignolles',
        pages: 4,
        confidential: false,
      },
      {
        id: 'doc-003-b',
        type: 'fiche_patient',
        label: 'Liste nominative résidents',
        reference: 'FSP-EHPAD-092',
        date: '2026-09-01',
        issuer: 'EHPAD Les Acacias — Direction médicale',
        pages: 2,
        confidential: true,
      },
    ],
  },
];

export const PRIORITY_CONFIG = {
  urgent: { label: 'Urgent', color: '#ef4444', bg: '#fef2f2', dot: 'bg-red-500' },
  standard: { label: 'Standard', color: '#2563eb', bg: '#eff6ff', dot: 'bg-blue-500' },
  low: { label: 'Faible', color: '#6b7280', bg: '#f9fafb', dot: 'bg-gray-400' },
};

export const STATUS_CONFIG = {
  nouveau: { label: 'Nouveau', color: '#7c3aed' },
  assigné: { label: 'Assigné', color: '#d97706' },
  en_transit: { label: 'En transit', color: '#0891b2' },
  livré: { label: 'Livré', color: '#059669' },
  annulé: { label: 'Annulé', color: '#ef4444' },
  suspendu: { label: 'Suspendu', color: '#f59e0b' },
};

export const DOC_CONFIG = {
  ordonnance: { icon: '📄', color: '#7c3aed', bg: '#f5f3ff', label: 'Ordonnance' },
  bon_livraison: { icon: '📋', color: '#0891b2', bg: '#ecfeff', label: 'Bon de livraison' },
  fiche_patient: { icon: '🏥', color: '#059669', bg: '#f0fdf4', label: 'Fiche patient' },
};
